"""
/// <summary>
/// ArioNex central audit logger (ArioNex Centralized Audit Logger)
/// </summary>
/// <remarks>
/// This module is responsible for recording all user interactions with the RAG system in the
/// pg_audit_logs table of the database. Every query submitted through any channel (REST API, Widget, Telegram)
/// is recorded in this table to enable auditing and analysis of user behavior.
///
/// Using this helper instead of duplicated code in each endpoint ensures the integrity of the data format.
/// Audit logging errors are logged silently so the main response is not disrupted.
/// </remarks>
"""

import logging
from app.core.database import get_db_connection

logger = logging.getLogger("arionex.audit_logger")

# SQL statement for audit log insertion — usable in any channel
_AUDIT_INSERT_SQL = """
INSERT INTO pg_audit_logs (user_name, user_role, query_text, response_text, status, pii_masked_count, total_tokens, input_tokens, output_tokens, response_time_ms, agent_type)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""


def log_audit_event(
    user_name: str,
    user_role: str,
    query_text: str,
    response_text: str,
    status: str = "success",
    pii_masked_count: int = 0,
    total_tokens: int = 0,
    input_tokens: int = 0,
    output_tokens: int = 0,
    response_time_ms: int = 0,
    agent_type: str = "rag",
) -> None:
    """
    /// <summary>
    /// Logs a user interaction event in the central audit table pg_audit_logs
    /// </summary>
    /// <param name="user_name">User name or identifier (e.g. "API_User", "Widget_User")</param>
    /// <param name="user_role">User role in the system (e.g. "Developer", "Viewer", "Admin")</param>
    /// <param name="query_text">Text of the query submitted by the user</param>
    /// <param name="response_text">Text of the response generated by the RAG system</param>
    /// <param name="status">Response status — "success" or "error" (default: "success")</param>
    /// <param name="pii_masked_count">Number of masked sensitive data items (default: 0)</param>
    /// <remarks>
    /// This function runs inside a guarded try-except block so that database errors do not interrupt
    /// the main response to the user. Errors are only recorded in the log.
    /// </remarks>
    """
    try:
        conn = get_db_connection()
        with conn.cursor() as cur:
            cur.execute(_AUDIT_INSERT_SQL, (
                user_name,
                user_role,
                query_text,
                response_text,
                status,
                pii_masked_count,
                total_tokens,
                input_tokens,
                output_tokens,
                response_time_ms,
                agent_type,
            ))
            conn.commit()
        conn.close()
    except Exception as e:
        logger.error(f"Audit log insertion failed (non-critical): {str(e)}")
