"""
/// <summary>
/// ArioNex Telegram Bot Integration module
/// </summary>
/// <remarks>
/// This module manages the Telegram bot connected to the smart RAG engine asynchronously.
/// The bot can understand conversation history per user identifier (chat_id),
/// invoke the semantic and computational aggregator, and respond accurately with citations to sources.
/// </remarks>
"""

import asyncio
import logging
from typing import Dict, List
from telegram import Update
from telegram.ext import Application, ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters

from app.core.config import settings
from app.services.retrieval import synthesize_rag_response

logger = logging.getLogger("arionex.telegram_bot")

# In-memory Chat Session Store per Telegram user
# Each session contains a list of message dictionaries in the form [{"Human": "..."}, {"AI": "..."}].
_chat_sessions: Dict[int, List[dict]] = {}

# Main reference to the Telegram application object to control its lifecycle in the start and stop methods
telegram_app: Application = None

def get_chat_history(chat_id: int) -> List[dict]:
    """
    /// <summary>
    /// Retrieve the Telegram user's past conversation history with a history-length limit applied
    /// </summary>
    /// <param name="chat_id">Unique conversation identifier in Telegram</param>
    /// <returns>List of recently exchanged messages</returns>
    """
    if chat_id not in _chat_sessions:
        _chat_sessions[chat_id] = []
    # Limit history to the 10 most recent messages to optimize token consumption
    return _chat_sessions[chat_id][-10:]

def update_chat_history(chat_id: int, user_query: str, ai_response: str):
    """
    /// <summary>
    /// Add a new question and answer to the Telegram user's session history
    /// </summary>
    /// <param name="chat_id">Unique conversation identifier in Telegram</param>
    /// <param name="user_query">Question asked by the user</param>
    /// <param name="ai_response">Response generated by the ArioNex assistant</param>
    /// </summary>
    """
    if chat_id not in _chat_sessions:
        _chat_sessions[chat_id] = []
    
    _chat_sessions[chat_id].append({"Human": user_query})
    _chat_sessions[chat_id].append({"AI": ai_response})

async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    /// <summary>
    /// Handler for the bot's start command (/start)
    /// </summary>
    """
    chat_id = update.effective_chat.id
    # Clear past history on restart
    if chat_id in _chat_sessions:
        _chat_sessions[chat_id] = []
        
    welcome_text = (
        "💼 **به دستیار هوشمند سازمانی آریونکس (ArioNex) خوش آمدید!** ✨\n\n"
        "من دستیار هوش مصنوعی سازمان شما هستم و می‌توانم به صورت کاملاً امن "
        "به جستجوی اسناد، قوانین و تحلیل داده‌های مالی و حسابداری بپردازم.\n\n"
        "💬 **چگونه می‌توانم به شما کمک کنم؟**\n"
        "کافیست سوال خود را بنویسید یا اسناد مالی را جهت تحلیل مطرح نمایید."
    )
    await update.message.reply_text(welcome_text, parse_mode="Markdown")
    logger.info(f"Telegram user {chat_id} started the conversation bot.")

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    /// <summary>
    /// Handler for the bot's help command (/help)
    /// </summary>
    """
    help_text = (
        "📚 **راهنمای استفاده از دستیار آریونکس (ArioNex Help):**\n\n"
        "🔹 **پرسش معنایی اسناد:** سوالات خود را درباره مفاد قراردادها، فایل‌های متنی یا پی‌دی‌اف‌های بارگذاری شده در سیستم بپرسید.\n"
        "🔹 **تحلیل آماری حسابداری:** با استفاده از کلیدواژه‌هایی چون *میانگین، مجموع، فاکتور، سند، تراکنش* می‌توانید داده‌های مالی دمو را تحلیل کنید.\n"
        "🔹 **قانون عدم توهم:** دستیار بر اساس مستندات واقعی پاسخ می‌دهد. در صورت نبود منابع، از ارائه حدس و توهم خودداری خواهد کرد.\n\n"
        "🔄 برای بازنشانی کامل تاریخچه چت جاری، دستور /start را ارسال کنید."
    )
    await update.message.reply_text(help_text, parse_mode="Markdown")

async def message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    /// <summary>
    /// Main handler for incoming text messages from Telegram users and connection to the RAG engine
    /// </summary>
    """
    if not update.message or not update.message.text:
        return
        
    chat_id = update.effective_chat.id
    user_text = update.message.text.strip()
    
    logger.info(f"Received Telegram message from user {chat_id}: '{user_text[:30]}...'")
    
    # Show the typing status to the Telegram user
    await context.bot.send_chat_action(chat_id=chat_id, action="typing")
    
    try:
        # 1. Load the conversation session history by chat_id
        history = get_chat_history(chat_id)
        
        # 2. Invoke the centralized smart RAG engine
        result = synthesize_rag_response(
            user_input=user_text,
            chat_history=history,
            threshold=0.4,
            k=4,
            session_id=str(chat_id)
        )
        
        answer = result.get("answer", "")
        sources = result.get("sources", [])
        
        # 3. Add the cited sources in a polished format at the bottom of the Telegram reply
        if sources and "اطلاعات کافی" not in answer:
            citation_list = []
            seen_sources = set()
            for src in sources:
                src_key = f"{src['name']} ({src['page']})"
                if src_key not in seen_sources:
                    seen_sources.add(src_key)
                    citation_list.append(f"🔹 {src['name']} - {src['page']}")
            
            if citation_list:
                answer += "\n\n📚 **منابع استناد شده:**\n" + "\n".join(citation_list)
        
        # 4. Store the interaction in the conversation session
        update_chat_history(chat_id, user_text, result.get("answer", ""))
        
        # 5. Send the final reply
        await update.message.reply_text(answer, parse_mode="Markdown")
        logger.info(f"Replied successfully to Telegram user {chat_id}.")
        
    except Exception as e:
        logger.error(f"Error handling Telegram message for user {chat_id}: {str(e)}")
        error_reply = "⚠️ متاسفانه در پردازش پاسخ شما خطایی در موتور هوش مصنوعی رخ داده است. لطفاً مجدداً تلاش فرمایید."
        await update.message.reply_text(error_reply)

async def init_telegram_bot() -> Application:
    """
    /// <summary>
    /// Initialize and register the various message and command handlers for the Telegram bot
    /// </summary>
    /// <returns>A valid Application instance from the Telegram library</returns>
    """
    token = settings.telegram_bot_token
    if not token:
        logger.warning("TELEGRAM_BOT_TOKEN is empty. Telegram integration will remain inactive.")
        return None
        
    try:
        app = ApplicationBuilder().token(token).build()
        
        # Register command handlers
        app.add_handler(CommandHandler("start", start_command))
        app.add_handler(CommandHandler("help", help_command))
        
        # Register a handler for all miscellaneous text messages
        app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, message_handler))
        
        logger.info("Telegram Bot Application initialized with handlers successfully.")
        return app
    except Exception as e:
        logger.error(f"Failed to initialize Telegram Bot application builder: {str(e)}")
        return None

async def start_telegram_bot_service():
    """
    /// <summary>
    /// Launch and start the Telegram bot message-receiving process (Non-blocking Polling) within the FastAPI lifespan
    /// </summary>
    """
    global telegram_app
    
    # Check whether the Telegram toggle feature is enabled in the admin settings
    if not settings.integrations.telegram_bot:
        logger.info("Telegram Bot integration is disabled in settings. Skipping startup.")
        return
        
    telegram_app = await init_telegram_bot()
    if not telegram_app:
        logger.warning("Telegram Bot application could not be built. Skipping bot runner.")
        return
        
    try:
        logger.info("Starting Telegram Bot Polling service...")
        # Asynchronously run the bot's internal routines inside the FastAPI web server
        await telegram_app.initialize()
        await telegram_app.start()
        await telegram_app.updater.start_polling(drop_pending_updates=True)
        logger.info("Telegram Bot is online and actively polling.")
    except Exception as e:
        logger.error(f"Graceful start failed for Telegram Bot service: {str(e)}. Web server will continue operating normally.")

async def stop_telegram_bot_service():
    """
    /// <summary>
    /// Shut down and stop the Telegram bot asynchronously when the FastAPI server is stopped
    /// </summary>
    """
    global telegram_app
    if telegram_app:
        try:
            logger.info("Stopping Telegram Bot polling service...")
            if telegram_app.updater:
                await telegram_app.updater.stop()
            await telegram_app.stop()
            await telegram_app.shutdown()
            logger.info("Telegram Bot service stopped and resources freed successfully.")
        except Exception as e:
            logger.error(f"Error during Telegram Bot shutdown sequence: {str(e)}")
