from pathlib import Path
import zipfile, html, os, shutil, re, csv
OUT=Path(__file__).parent
ROOT=OUT.parent.parent
# Binary assets are intentionally not copied into docs/pitch-deck because
# the PR flow does not support newly added binary files. The HTML deck
# references the existing repository images instead.
brand='#0f1b33'; gold='#c57b42'; cream='#f7f4ed'; green='#1b7f3a'
slides=[
('آریونکس | ArioNex','دستیار هوش مصنوعی امن برای دانش سازمانی فارسی','سرمایه‌گذاری روی محصولی آماده پایلوت برای شرکت‌های فناوری و مراکز پشتیبانی'),
('مسئله','دانش سازمانی در فایل‌ها، پیام‌ها و ابزارهای جداگانه پراکنده است.','کارمند برای یک پاسخ ساده باید بین PDF، Word، Excel، لاگ پشتیبانی و پیام‌رسان‌ها جست‌وجو کند؛ نتیجه: اتلاف زمان، پاسخ‌های ناسازگار و ریسک امنیت داده.'),
('راه‌حل','یک دستیار AI سازمانی که با اسناد داخلی شرکت کار می‌کند.','آریونکس اسناد را دریافت، پاک‌سازی، ایمن‌سازی و قابل پرسش‌وپاسخ می‌کند؛ خروجی برای کاربر، یک پاسخ سریع و قابل اتکا در محیطی اختصاصی است.'),
('ارزش پیشنهادی','پاسخ امن، سریع و فارسی از دل دانش داخلی سازمان.','برای شرکت‌های فناوری و مراکز پشتیبانی: کاهش زمان جست‌وجو، کاهش فشار روی تیم پشتیبانی، پاسخ‌های یکپارچه و امکان اتصال به ابزارهای داخلی.'),
('محصول و MVP','دموی محصول بالا آمده و چند کاربر تستی آن را بررسی کرده‌اند.','پشتیبانی از PDF، Word، Excel و CSV؛ جست‌وجوی معنایی، چت با اسناد، داشبورد مدیریتی، API، مدیریت دسترسی، ماسک PII و آمادگی برای پایلوت سازمانی یک‌ماهه.'),
('نمای محصول','داشبوردی برای کنترل دانش، امنیت و مصرف.','نمای مدیریتی آریونکس شاخص‌هایی مثل اسناد ایندکس‌شده، پرسش‌های امروز، مصرف API، وضعیت پردازش و سلامت جریان داده را نشان می‌دهد.'),
('بازار هدف','شروع از ایران؛ تمرکز اولیه روی شرکت‌های فناوری و SaaS.','بازار در دسترس اولیه: سازمان‌هایی که اسناد زیاد، تیم پشتیبانی فعال و نیاز جدی به پاسخ‌گویی داخلی دارند. هدف سه‌ساله: ۳۰ تا ۵۰ مشتری سازمانی پایدار.'),
('مدل کسب‌وکار','ترکیب لایسنس، اشتراک و مصرف API.','پایلوت یک‌ماهه سازمانی؛ اشتراک ماهانه بر اساس کاربر و مصرف؛ لایسنس Enterprise برای استقرار اختصاصی؛ قیمت‌گذاری پیشنهادی متناسب با حجم اسناد، تعداد کاربران و سطح SLA.'),
('رقابت و تمایز','رقبا وجود دارند؛ اما تمرکز آریونکس روی امنیت، فارسی و یکپارچگی سازمانی است.','در کنار راهکارهایی مثل گفتا، متیس، یارابات، دستیارینو و ابزارهای جهانی، آریونکس روی مدیریت دانش داخلی، استقرار اختصاصی، بهینه‌سازی فارسی و اتصال به ابزارهای ایرانی مثل بله متمرکز است.'),
('ورود به بازار','فروش B2B با پایلوت کم‌ریسک و تبدیل به قرارداد.','ماه ۱ تا ۳: ۳ تا ۵ پایلوت هدفمند. ماه ۳ تا ۶: تبدیل پایلوت‌ها به قرارداد. ماه ۶ تا ۱۲: همکاری با شرکت‌های نرم‌افزاری و فروش کانالی.'),
('درخواست سرمایه و مالی','درآمد فعلی صفر؛ تمرکز روی تبدیل MVP به پایلوت پولی.','پیشنهاد سرمایه اولیه: ۱.۵ میلیارد تومان برای ۱۲ ماه runway؛ هزینه‌کرد: محصول و API، فروش B2B، نیروی انسانی، سرور و امنیت، ثبت شرکت و حقوقی.'),
('تیم و جمع‌بندی','تیمی کوچک با تجربه LLM فارسی، نرم‌افزار و محصول AI.','زهرا رفیعی، مسئول فنی و مهندس نرم‌افزار در سرچیا. عارفه ضرابیان، مسئول محصول و تصمیم‌گیری و مهندس هوش مصنوعی در پدیده عصر فناوری. سابقه رتبه چهارم مسابقه همراه اول با مدل دفاعی سبک و سریع Gemma 2.')]
# HTML
html_slides='\n'.join([f'''<section class="slide"><div><p class="kicker">{i:02d}</p><h1>{html.escape(t)}</h1><h2>{html.escape(s)}</h2><p>{html.escape(b)}</p>{'<img class="shot" src="../../product_screenshot.jpg">' if i==6 else ''}{'<img class="arch" src="../../mermaid-diagram-2026-06-07-092055.png">' if i==9 else ''}</div></section>''' for i,(t,s,b) in enumerate(slides,1)])
(OUT/'pitch-deck-fa.html').write_text(f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>Pitch Deck آریونکس</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;600;700;800;900&display=swap" rel="stylesheet"><style>body{{margin:0;background:#111;font-family:Vazirmatn,Tahoma,sans-serif;color:{brand}}}.slide{{width:1280px;height:720px;box-sizing:border-box;padding:58px 72px;background:linear-gradient(135deg,{cream},#fff);page-break-after:always;display:flex;align-items:center;position:relative;overflow:hidden}}.slide:before{{content:"";position:absolute;inset:auto -120px -160px auto;width:420px;height:420px;border-radius:50%;background:{gold};opacity:.16}}.kicker{{color:{gold};font-weight:900;letter-spacing:2px}}h1{{font-size:56px;line-height:1.15;margin:0 0 22px;font-weight:900}}h2{{font-size:31px;line-height:1.45;margin:0 0 24px;color:{gold};font-weight:800;max-width:980px}}p{{font-size:27px;line-height:1.8;max-width:980px;margin:0}}.shot{{position:absolute;left:70px;bottom:48px;width:560px;border-radius:22px;box-shadow:0 20px 60px #0f1b3340}}.arch{{position:absolute;left:70px;bottom:50px;width:470px;max-height:300px;object-fit:contain;border-radius:16px;background:#fff;box-shadow:0 15px 45px #0f1b3330}}@media print{{body{{background:white}}.slide{{break-after:page}}}}</style></head><body>{html_slides}</body></html>''',encoding='utf-8')
# outline/transcript
outline=[]; transcript=[]
for i,(t,s,b) in enumerate(slides,1):
    outline.append(f"## اسلاید {i}: {t}\n- پیام اصلی: {s}\n- نکات ارائه: {b}\n")
    transcript.append(f"## متن ارائه اسلاید {i}: {t}\n{s}\n\n{b}\n")
(OUT/'pitch-deck-outline-fa.md').write_text('# طرح ۱۲ اسلایدی Pitch Deck آریونکس\n\n'+ '\n'.join(outline),encoding='utf-8')
(OUT/'pitch-deck-transcript-fa.md').write_text('# متن پیشنهادی ارائه Pitch Deck آریونکس\n\n'+ '\n'.join(transcript),encoding='utf-8')
# financial markdown + csv
rows=[['سناریو','تعداد مشتری سال ۱','درآمد سال ۱','درآمد سال ۳','فرض کلیدی'],['بدبینانه','3','540,000,000','2,400,000,000','فروش آهسته و پایلوت‌های محدود'],['واقع‌بینانه','8','1,680,000,000','7,200,000,000','تبدیل بخشی از پایلوت‌ها به قرارداد'],['خوش‌بینانه','15','3,600,000,000','15,000,000,000','فروش کانالی و رشد سریع B2B']]
with open(OUT/'financial-report-fa.csv','w',newline='',encoding='utf-8-sig') as f: csv.writer(f).writerows(rows)
fin='''# گزارش مالی و سرمایه‌گذاری آریونکس\n\n## خلاصه سرمایه‌گذاری\n- سرمایه پیشنهادی: ۱.۵ میلیارد تومان برای ۱۲ ماه runway.\n- ارزش‌گذاری پیشنهادی اولیه: بازه ۴.۵ تا ۶ میلیارد تومان، با اتکا به MVP، تیم، تجربه LLM فارسی و آمادگی پایلوت.\n- درآمد فعلی: صفر؛ تمرکز فعلی روی پایلوت سازمانی و فروش B2B است.\n\n## هزینه‌کرد پیشنهادی سرمایه\n| ردیف | حوزه | سهم | مبلغ تقریبی |\n|---|---:|---:|---:|\n| ۱ | توسعه محصول، API و بهینه‌سازی مدل | ۳۰٪ | ۴۵۰ میلیون تومان |\n| ۲ | فروش B2B و بازاریابی هدفمند | ۲۵٪ | ۳۷۵ میلیون تومان |\n| ۳ | نیروی انسانی فنی و محصول | ۲۵٪ | ۳۷۵ میلیون تومان |\n| ۴ | سرور، امنیت و زیرساخت | ۱۰٪ | ۱۵۰ میلیون تومان |\n| ۵ | ثبت شرکت، حقوقی و عملیات | ۱۰٪ | ۱۵۰ میلیون تومان |\n\n## سناریوهای درآمدی\n| سناریو | مشتری سال اول | درآمد سال اول | درآمد سال سوم |\n|---|---:|---:|---:|\n| بدبینانه | ۳ | ۵۴۰ میلیون تومان | ۲.۴ میلیارد تومان |\n| واقع‌بینانه | ۸ | ۱.۶۸ میلیارد تومان | ۷.۲ میلیارد تومان |\n| خوش‌بینانه | ۱۵ | ۳.۶ میلیارد تومان | ۱۵ میلیارد تومان |\n\n## مدل قیمت‌گذاری پیشنهادی\n- پایلوت یک‌ماهه سازمانی: ۴۰ تا ۸۰ میلیون تومان.\n- اشتراک ماهانه سازمانی: ۳۰ تا ۱۸۰ میلیون تومان بر اساس تعداد کاربر، حجم سند و مصرف API.\n- لایسنس Enterprise و استقرار اختصاصی: از ۵۰۰ میلیون تومان به بالا.\n- مصرف API/توکن: قیمت‌گذاری شناور بر اساس حجم پردازش.\n\n## رقبا و منابع بررسی بازار\n- گفتا: https://gofta.ir/\n- متیس: https://ir.linkedin.com/company/metis-ai-ir\n- یارابات: https://yarabot.ir/\n- دستیارینو: https://dastyarino.com/\n- رایورز AI: https://airayvarz.com/\n'''
(OUT/'financial-report-fa.md').write_text(fin,encoding='utf-8')
print('generated text-only pitch deck materials')
